//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SoftBottin.wsSoftBottin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoftBottinSoap", Namespace="http://tempuri.org/")]
    public partial class SoftBottin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetShoesByTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddShoeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddShoeDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddImageShoeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddShoeTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShoesTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShoesTypesByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditShoeTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteShoeTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetColorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetColorByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddColorOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditColorOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteColorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEmailNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SigInOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SoftBottin() {
            this.Url = global::SoftBottin.Properties.Settings.Default.SoftBottin_wsSoftBottin_SoftBottin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetShoesByTypeCompletedEventHandler GetShoesByTypeCompleted;
        
        /// <remarks/>
        public event AddShoeCompletedEventHandler AddShoeCompleted;
        
        /// <remarks/>
        public event AddShoeDetailCompletedEventHandler AddShoeDetailCompleted;
        
        /// <remarks/>
        public event AddImageShoeCompletedEventHandler AddImageShoeCompleted;
        
        /// <remarks/>
        public event AddShoeTypeCompletedEventHandler AddShoeTypeCompleted;
        
        /// <remarks/>
        public event GetShoesTypesCompletedEventHandler GetShoesTypesCompleted;
        
        /// <remarks/>
        public event GetShoesTypesByIdCompletedEventHandler GetShoesTypesByIdCompleted;
        
        /// <remarks/>
        public event EditShoeTypeCompletedEventHandler EditShoeTypeCompleted;
        
        /// <remarks/>
        public event DeleteShoeTypeCompletedEventHandler DeleteShoeTypeCompleted;
        
        /// <remarks/>
        public event GetColorsCompletedEventHandler GetColorsCompleted;
        
        /// <remarks/>
        public event GetColorByIdCompletedEventHandler GetColorByIdCompleted;
        
        /// <remarks/>
        public event AddColorCompletedEventHandler AddColorCompleted;
        
        /// <remarks/>
        public event EditColorCompletedEventHandler EditColorCompleted;
        
        /// <remarks/>
        public event DeleteColorCompletedEventHandler DeleteColorCompleted;
        
        /// <remarks/>
        public event GetProductsCompletedEventHandler GetProductsCompleted;
        
        /// <remarks/>
        public event GetProductByIdCompletedEventHandler GetProductByIdCompleted;
        
        /// <remarks/>
        public event AddEmailNewUserCompletedEventHandler AddEmailNewUserCompleted;
        
        /// <remarks/>
        public event SigInCompletedEventHandler SigInCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShoesByType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetShoesByType(int iShoeType, out System.Data.DataSet dsShoes, out string sErrMessage) {
            object[] results = this.Invoke("GetShoesByType", new object[] {
                        iShoeType});
            dsShoes = ((System.Data.DataSet)(results[1]));
            sErrMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetShoesByTypeAsync(int iShoeType) {
            this.GetShoesByTypeAsync(iShoeType, null);
        }
        
        /// <remarks/>
        public void GetShoesByTypeAsync(int iShoeType, object userState) {
            if ((this.GetShoesByTypeOperationCompleted == null)) {
                this.GetShoesByTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShoesByTypeOperationCompleted);
            }
            this.InvokeAsync("GetShoesByType", new object[] {
                        iShoeType}, this.GetShoesByTypeOperationCompleted, userState);
        }
        
        private void OnGetShoesByTypeOperationCompleted(object arg) {
            if ((this.GetShoesByTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShoesByTypeCompleted(this, new GetShoesByTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddShoe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddShoe(string sName, string sDescription, string sRef, int iQuantityExisting, int iQuantitySold, int iPurchasePrice, int iSalePrice, int iShoeType, out int iIdInsert, out string sErrMessage) {
            object[] results = this.Invoke("AddShoe", new object[] {
                        sName,
                        sDescription,
                        sRef,
                        iQuantityExisting,
                        iQuantitySold,
                        iPurchasePrice,
                        iSalePrice,
                        iShoeType});
            iIdInsert = ((int)(results[1]));
            sErrMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddShoeAsync(string sName, string sDescription, string sRef, int iQuantityExisting, int iQuantitySold, int iPurchasePrice, int iSalePrice, int iShoeType) {
            this.AddShoeAsync(sName, sDescription, sRef, iQuantityExisting, iQuantitySold, iPurchasePrice, iSalePrice, iShoeType, null);
        }
        
        /// <remarks/>
        public void AddShoeAsync(string sName, string sDescription, string sRef, int iQuantityExisting, int iQuantitySold, int iPurchasePrice, int iSalePrice, int iShoeType, object userState) {
            if ((this.AddShoeOperationCompleted == null)) {
                this.AddShoeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddShoeOperationCompleted);
            }
            this.InvokeAsync("AddShoe", new object[] {
                        sName,
                        sDescription,
                        sRef,
                        iQuantityExisting,
                        iQuantitySold,
                        iPurchasePrice,
                        iSalePrice,
                        iShoeType}, this.AddShoeOperationCompleted, userState);
        }
        
        private void OnAddShoeOperationCompleted(object arg) {
            if ((this.AddShoeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddShoeCompleted(this, new AddShoeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddShoeDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddShoeDetail(int iIdShoe, int iIdColor, int iSize, int iQuantity, int iQuantityExisting, int iQuantitySold, out string sErrMessage) {
            object[] results = this.Invoke("AddShoeDetail", new object[] {
                        iIdShoe,
                        iIdColor,
                        iSize,
                        iQuantity,
                        iQuantityExisting,
                        iQuantitySold});
            sErrMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddShoeDetailAsync(int iIdShoe, int iIdColor, int iSize, int iQuantity, int iQuantityExisting, int iQuantitySold) {
            this.AddShoeDetailAsync(iIdShoe, iIdColor, iSize, iQuantity, iQuantityExisting, iQuantitySold, null);
        }
        
        /// <remarks/>
        public void AddShoeDetailAsync(int iIdShoe, int iIdColor, int iSize, int iQuantity, int iQuantityExisting, int iQuantitySold, object userState) {
            if ((this.AddShoeDetailOperationCompleted == null)) {
                this.AddShoeDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddShoeDetailOperationCompleted);
            }
            this.InvokeAsync("AddShoeDetail", new object[] {
                        iIdShoe,
                        iIdColor,
                        iSize,
                        iQuantity,
                        iQuantityExisting,
                        iQuantitySold}, this.AddShoeDetailOperationCompleted, userState);
        }
        
        private void OnAddShoeDetailOperationCompleted(object arg) {
            if ((this.AddShoeDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddShoeDetailCompleted(this, new AddShoeDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddImageShoe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddImageShoe(int iIdShoe, string sName, string sType, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] btFileByte, out string sErrMessage) {
            object[] results = this.Invoke("AddImageShoe", new object[] {
                        iIdShoe,
                        sName,
                        sType,
                        btFileByte});
            sErrMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddImageShoeAsync(int iIdShoe, string sName, string sType, byte[] btFileByte) {
            this.AddImageShoeAsync(iIdShoe, sName, sType, btFileByte, null);
        }
        
        /// <remarks/>
        public void AddImageShoeAsync(int iIdShoe, string sName, string sType, byte[] btFileByte, object userState) {
            if ((this.AddImageShoeOperationCompleted == null)) {
                this.AddImageShoeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddImageShoeOperationCompleted);
            }
            this.InvokeAsync("AddImageShoe", new object[] {
                        iIdShoe,
                        sName,
                        sType,
                        btFileByte}, this.AddImageShoeOperationCompleted, userState);
        }
        
        private void OnAddImageShoeOperationCompleted(object arg) {
            if ((this.AddImageShoeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddImageShoeCompleted(this, new AddImageShoeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddShoeType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddShoeType(string sName, string sDescription, string sRef, out string sErrMessage) {
            object[] results = this.Invoke("AddShoeType", new object[] {
                        sName,
                        sDescription,
                        sRef});
            sErrMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddShoeTypeAsync(string sName, string sDescription, string sRef) {
            this.AddShoeTypeAsync(sName, sDescription, sRef, null);
        }
        
        /// <remarks/>
        public void AddShoeTypeAsync(string sName, string sDescription, string sRef, object userState) {
            if ((this.AddShoeTypeOperationCompleted == null)) {
                this.AddShoeTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddShoeTypeOperationCompleted);
            }
            this.InvokeAsync("AddShoeType", new object[] {
                        sName,
                        sDescription,
                        sRef}, this.AddShoeTypeOperationCompleted, userState);
        }
        
        private void OnAddShoeTypeOperationCompleted(object arg) {
            if ((this.AddShoeTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddShoeTypeCompleted(this, new AddShoeTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShoesTypes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetShoesTypes(out System.Data.DataSet dsShoesTypes, out string sErrMessage) {
            object[] results = this.Invoke("GetShoesTypes", new object[0]);
            dsShoesTypes = ((System.Data.DataSet)(results[1]));
            sErrMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetShoesTypesAsync() {
            this.GetShoesTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetShoesTypesAsync(object userState) {
            if ((this.GetShoesTypesOperationCompleted == null)) {
                this.GetShoesTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShoesTypesOperationCompleted);
            }
            this.InvokeAsync("GetShoesTypes", new object[0], this.GetShoesTypesOperationCompleted, userState);
        }
        
        private void OnGetShoesTypesOperationCompleted(object arg) {
            if ((this.GetShoesTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShoesTypesCompleted(this, new GetShoesTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShoesTypesById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetShoesTypesById(int iShoeType, out System.Data.DataSet dsShoesTypes, out string sErrMessage) {
            object[] results = this.Invoke("GetShoesTypesById", new object[] {
                        iShoeType});
            dsShoesTypes = ((System.Data.DataSet)(results[1]));
            sErrMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetShoesTypesByIdAsync(int iShoeType) {
            this.GetShoesTypesByIdAsync(iShoeType, null);
        }
        
        /// <remarks/>
        public void GetShoesTypesByIdAsync(int iShoeType, object userState) {
            if ((this.GetShoesTypesByIdOperationCompleted == null)) {
                this.GetShoesTypesByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShoesTypesByIdOperationCompleted);
            }
            this.InvokeAsync("GetShoesTypesById", new object[] {
                        iShoeType}, this.GetShoesTypesByIdOperationCompleted, userState);
        }
        
        private void OnGetShoesTypesByIdOperationCompleted(object arg) {
            if ((this.GetShoesTypesByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShoesTypesByIdCompleted(this, new GetShoesTypesByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditShoeType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EditShoeType(int iId, string sName, string sDescription, string sRef, out string sErrMessage) {
            object[] results = this.Invoke("EditShoeType", new object[] {
                        iId,
                        sName,
                        sDescription,
                        sRef});
            sErrMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EditShoeTypeAsync(int iId, string sName, string sDescription, string sRef) {
            this.EditShoeTypeAsync(iId, sName, sDescription, sRef, null);
        }
        
        /// <remarks/>
        public void EditShoeTypeAsync(int iId, string sName, string sDescription, string sRef, object userState) {
            if ((this.EditShoeTypeOperationCompleted == null)) {
                this.EditShoeTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditShoeTypeOperationCompleted);
            }
            this.InvokeAsync("EditShoeType", new object[] {
                        iId,
                        sName,
                        sDescription,
                        sRef}, this.EditShoeTypeOperationCompleted, userState);
        }
        
        private void OnEditShoeTypeOperationCompleted(object arg) {
            if ((this.EditShoeTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditShoeTypeCompleted(this, new EditShoeTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteShoeType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteShoeType(int iId, out string sErrMessage) {
            object[] results = this.Invoke("DeleteShoeType", new object[] {
                        iId});
            sErrMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteShoeTypeAsync(int iId) {
            this.DeleteShoeTypeAsync(iId, null);
        }
        
        /// <remarks/>
        public void DeleteShoeTypeAsync(int iId, object userState) {
            if ((this.DeleteShoeTypeOperationCompleted == null)) {
                this.DeleteShoeTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteShoeTypeOperationCompleted);
            }
            this.InvokeAsync("DeleteShoeType", new object[] {
                        iId}, this.DeleteShoeTypeOperationCompleted, userState);
        }
        
        private void OnDeleteShoeTypeOperationCompleted(object arg) {
            if ((this.DeleteShoeTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteShoeTypeCompleted(this, new DeleteShoeTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetColors", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetColors(out System.Data.DataSet dsColors, out string sErrMessage) {
            object[] results = this.Invoke("GetColors", new object[0]);
            dsColors = ((System.Data.DataSet)(results[1]));
            sErrMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetColorsAsync() {
            this.GetColorsAsync(null);
        }
        
        /// <remarks/>
        public void GetColorsAsync(object userState) {
            if ((this.GetColorsOperationCompleted == null)) {
                this.GetColorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetColorsOperationCompleted);
            }
            this.InvokeAsync("GetColors", new object[0], this.GetColorsOperationCompleted, userState);
        }
        
        private void OnGetColorsOperationCompleted(object arg) {
            if ((this.GetColorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetColorsCompleted(this, new GetColorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetColorById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetColorById(int iColorId, out System.Data.DataSet dsColors, out string sErrMessage) {
            object[] results = this.Invoke("GetColorById", new object[] {
                        iColorId});
            dsColors = ((System.Data.DataSet)(results[1]));
            sErrMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetColorByIdAsync(int iColorId) {
            this.GetColorByIdAsync(iColorId, null);
        }
        
        /// <remarks/>
        public void GetColorByIdAsync(int iColorId, object userState) {
            if ((this.GetColorByIdOperationCompleted == null)) {
                this.GetColorByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetColorByIdOperationCompleted);
            }
            this.InvokeAsync("GetColorById", new object[] {
                        iColorId}, this.GetColorByIdOperationCompleted, userState);
        }
        
        private void OnGetColorByIdOperationCompleted(object arg) {
            if ((this.GetColorByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetColorByIdCompleted(this, new GetColorByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddColor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddColor(string sDescription, string sRGB, out string sErrMessage) {
            object[] results = this.Invoke("AddColor", new object[] {
                        sDescription,
                        sRGB});
            sErrMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddColorAsync(string sDescription, string sRGB) {
            this.AddColorAsync(sDescription, sRGB, null);
        }
        
        /// <remarks/>
        public void AddColorAsync(string sDescription, string sRGB, object userState) {
            if ((this.AddColorOperationCompleted == null)) {
                this.AddColorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddColorOperationCompleted);
            }
            this.InvokeAsync("AddColor", new object[] {
                        sDescription,
                        sRGB}, this.AddColorOperationCompleted, userState);
        }
        
        private void OnAddColorOperationCompleted(object arg) {
            if ((this.AddColorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddColorCompleted(this, new AddColorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditColor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EditColor(int iId, string sDescription, string sRGB, out string sErrMessage) {
            object[] results = this.Invoke("EditColor", new object[] {
                        iId,
                        sDescription,
                        sRGB});
            sErrMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EditColorAsync(int iId, string sDescription, string sRGB) {
            this.EditColorAsync(iId, sDescription, sRGB, null);
        }
        
        /// <remarks/>
        public void EditColorAsync(int iId, string sDescription, string sRGB, object userState) {
            if ((this.EditColorOperationCompleted == null)) {
                this.EditColorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditColorOperationCompleted);
            }
            this.InvokeAsync("EditColor", new object[] {
                        iId,
                        sDescription,
                        sRGB}, this.EditColorOperationCompleted, userState);
        }
        
        private void OnEditColorOperationCompleted(object arg) {
            if ((this.EditColorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditColorCompleted(this, new EditColorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteColor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteColor(int iId, out string sErrMessage) {
            object[] results = this.Invoke("DeleteColor", new object[] {
                        iId});
            sErrMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteColorAsync(int iId) {
            this.DeleteColorAsync(iId, null);
        }
        
        /// <remarks/>
        public void DeleteColorAsync(int iId, object userState) {
            if ((this.DeleteColorOperationCompleted == null)) {
                this.DeleteColorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteColorOperationCompleted);
            }
            this.InvokeAsync("DeleteColor", new object[] {
                        iId}, this.DeleteColorOperationCompleted, userState);
        }
        
        private void OnDeleteColorOperationCompleted(object arg) {
            if ((this.DeleteColorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteColorCompleted(this, new DeleteColorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetProducts() {
            object[] results = this.Invoke("GetProducts", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsAsync() {
            this.GetProductsAsync(null);
        }
        
        /// <remarks/>
        public void GetProductsAsync(object userState) {
            if ((this.GetProductsOperationCompleted == null)) {
                this.GetProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsOperationCompleted);
            }
            this.InvokeAsync("GetProducts", new object[0], this.GetProductsOperationCompleted, userState);
        }
        
        private void OnGetProductsOperationCompleted(object arg) {
            if ((this.GetProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsCompleted(this, new GetProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetProductById(int iProductId) {
            object[] results = this.Invoke("GetProductById", new object[] {
                        iProductId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductByIdAsync(int iProductId) {
            this.GetProductByIdAsync(iProductId, null);
        }
        
        /// <remarks/>
        public void GetProductByIdAsync(int iProductId, object userState) {
            if ((this.GetProductByIdOperationCompleted == null)) {
                this.GetProductByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductByIdOperationCompleted);
            }
            this.InvokeAsync("GetProductById", new object[] {
                        iProductId}, this.GetProductByIdOperationCompleted, userState);
        }
        
        private void OnGetProductByIdOperationCompleted(object arg) {
            if ((this.GetProductByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductByIdCompleted(this, new GetProductByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddEmailNewUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddEmailNewUser(string sEmail, out string sErrMessage) {
            object[] results = this.Invoke("AddEmailNewUser", new object[] {
                        sEmail});
            sErrMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddEmailNewUserAsync(string sEmail) {
            this.AddEmailNewUserAsync(sEmail, null);
        }
        
        /// <remarks/>
        public void AddEmailNewUserAsync(string sEmail, object userState) {
            if ((this.AddEmailNewUserOperationCompleted == null)) {
                this.AddEmailNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEmailNewUserOperationCompleted);
            }
            this.InvokeAsync("AddEmailNewUser", new object[] {
                        sEmail}, this.AddEmailNewUserOperationCompleted, userState);
        }
        
        private void OnAddEmailNewUserOperationCompleted(object arg) {
            if ((this.AddEmailNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEmailNewUserCompleted(this, new AddEmailNewUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SigIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SigIn(string sUserName, string sPassword, out System.Data.DataSet dsUser, out string sErrMessage) {
            object[] results = this.Invoke("SigIn", new object[] {
                        sUserName,
                        sPassword});
            dsUser = ((System.Data.DataSet)(results[1]));
            sErrMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SigInAsync(string sUserName, string sPassword) {
            this.SigInAsync(sUserName, sPassword, null);
        }
        
        /// <remarks/>
        public void SigInAsync(string sUserName, string sPassword, object userState) {
            if ((this.SigInOperationCompleted == null)) {
                this.SigInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSigInOperationCompleted);
            }
            this.InvokeAsync("SigIn", new object[] {
                        sUserName,
                        sPassword}, this.SigInOperationCompleted, userState);
        }
        
        private void OnSigInOperationCompleted(object arg) {
            if ((this.SigInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SigInCompleted(this, new SigInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetShoesByTypeCompletedEventHandler(object sender, GetShoesByTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShoesByTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShoesByTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet dsShoes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddShoeCompletedEventHandler(object sender, AddShoeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddShoeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddShoeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int iIdInsert {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddShoeDetailCompletedEventHandler(object sender, AddShoeDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddShoeDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddShoeDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddImageShoeCompletedEventHandler(object sender, AddImageShoeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddImageShoeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddImageShoeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddShoeTypeCompletedEventHandler(object sender, AddShoeTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddShoeTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddShoeTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetShoesTypesCompletedEventHandler(object sender, GetShoesTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShoesTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShoesTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet dsShoesTypes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetShoesTypesByIdCompletedEventHandler(object sender, GetShoesTypesByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShoesTypesByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShoesTypesByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet dsShoesTypes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void EditShoeTypeCompletedEventHandler(object sender, EditShoeTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditShoeTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditShoeTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteShoeTypeCompletedEventHandler(object sender, DeleteShoeTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteShoeTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteShoeTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetColorsCompletedEventHandler(object sender, GetColorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetColorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetColorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet dsColors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetColorByIdCompletedEventHandler(object sender, GetColorByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetColorByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetColorByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet dsColors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddColorCompletedEventHandler(object sender, AddColorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddColorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddColorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void EditColorCompletedEventHandler(object sender, EditColorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditColorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditColorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteColorCompletedEventHandler(object sender, DeleteColorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteColorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteColorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetProductsCompletedEventHandler(object sender, GetProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetProductByIdCompletedEventHandler(object sender, GetProductByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddEmailNewUserCompletedEventHandler(object sender, AddEmailNewUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddEmailNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddEmailNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SigInCompletedEventHandler(object sender, SigInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SigInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SigInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet dsUser {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string sErrMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591